# Site wide configuration
title:            iLearn
description:
logo:             # 120x120 px default image used for Twitter summary card
teaser:           400x250.png # 400x250 px default teaser image used in image archive grid
locale:
url:              http://edhzsz.github.io #http://localhost:4000 #http://edhzsz.github.io
disqus-shortname: "limos-io"

# Site owner
owner:
  name:  			    "Edgar Hernandez"
  email:   			  edhzsz@gmail.com
  twitter:        edhzsz
  google:
    ad-client:    "ca-pub-9720253951703917"
    ad-slot:      "6510116046"
  bio:            "Professional Code Janitor, Sr Procrastinator, Jr Father."
  avatar:         limo.jpeg # 160x160 px image for author byline
  # Social networking links used in footer. Update and remove as you like.
  twitter:        edhzsz
  facebook:
  github:         https://github.com/edhzsz
  stackexchange:  http://stackoverflow.com/users/149885/edgar-hernandez
  linkedin:       https://at.linkedin.com/in/edhzsz
  instagram:
  flickr:         https://www.flickr.com/photos/capcamgto/
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/+EdgarSaidHernándezSánchez?rel=author

# Analytics and webmaster tools stuff goes here
google_analytics_tracking_id:   UA-48372898-1
google_analytics_default_url:  edhzsz.github.io
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Jekyll configuration
timezone:    Europe/Vienna
permalink:   pretty
host:        localhost

# defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "article"

exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
